---
name: Testing

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
            # Runs at every sunday 14:10
    - cron: "10 2 * * 0"

jobs:

  # Test the image builds and works correctly.
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Test building image.
        id: build_image
        run: docker build -t docker-centos7-ansible .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
  
      - name: Run the built image.
        id: run_image
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-centos7-ansible
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Verify Ansible is accessible in the built image.
        id: test_ansible
        run: docker exec --tty test-container env TERM=xterm ansible --version
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
